#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        2.5
bspc config window_gap          4
bspc config focused_border_color "#69f22e"
bspc config normal_border_color "#f29557" 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# Start i3blocks at the top and make it floating
bspc rule -a i3blocks float=on
bspc rule -a i3blocks rectangle=0x0+0+0

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
# Start polybar
if type "polybar" > /dev/null; then
   polybar &
fi
# Set Up Wallpaper
feh --bg-scale ~/wallpaper.jpg &

# Start i3blocks at the top of the screen
#i3blocks -c ~/.config/i3blocks/config &

